version: "3.3"
services:
    buildsection:
        image: build-agent:latest
        build:
            context: .
            dockerfile: ./build-agent/Dockerfile
    testsection:
        image: test-agent:latest
        build:
            context: .
            dockerfile: ./test-agent/Dockerfile
        depends_on:
            - buildsection
